//teams

export const TEAMS_FETCHING_DATA = 'TEAMS/FETCHING_DATA';
export const TEAMS_FETCHING_DATA_SUCCESS = 'TEAMS/FETCHING_DATA_SUCCESS';
export const TEAMS_FETCHING_DATA_FAILURE = 'TEAMS/FETCHING_DATA_FAILURE';

